---
version: "2.0"

services:
  akash:
    image: tombeynon/akash-archive-node:v0.0.2
    env:
      - AKASH_MONIKER=my-node-name
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    akash:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        akash:
          denom: uakt
          amount: 10

deployment:
  akash:
    dcloud:
      profile: akash
      count: 1
